---
application:
  name: "strapi"
  project: "strapi"
  organization: "QoveryCommunity"
  publicly_accessible: true
  cpu: "800m"
  ram: "512mb"
  start_timeout: "480s"
  storage:
  - name: "data"
    size: "5GB"
    type: "ssd"
    mount_point: "/srv/app"
databases:
- type: "POSTGRESQL"
  name: "my-psql"
  version: "12"
routers:
- name: "main"
  routes:
  - application_name: "strapi"
    paths:
    - "/*"
